name: Code Analysis

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install .NET Framework Developer Pack
        run: |
          wget -q https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net472-developer-pack-linux-x64-installer
          chmod +x net472-developer-pack-linux-x64-installer
          sudo ./net472-developer-pack-linux-x64-installer

      - name: Restore dependencies
        run: dotnet restore

      - name: Analyze code
        run: dotnet build /p:Analyzers=**/*.dll
