name: Analyze code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up .NET Framework SDK
        uses: microsoft/setup-msbuild@v1
        with:
          dotnet-version: '4.8'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore dependencies
        run: nuget restore

      - name: Build and analyze code
        run: msbuild /p:Analyzers=**/*.dll
